name: ASO_REBOOT_MONITOR

on:
  workflow_dispatch:
  schedule:
    # Проверка каждые 5 минут
    - cron: '*/5 * * * *'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: pip install google-play-scraper gspread requests pandas

      - name: Run Monitor
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
        run: python bot.py