name: ASO_Final_Monitor_V3

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  check-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install
        run: pip install google-play-scraper gspread requests pandas

      - name: Run
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
        run: python bot.py